package CSCB525.FN099857.Tansport.Company.mtv;
/**
 * Enumeration representing the different types of vehicles.
 */
public enum VehicleType {
    TRUCK, TRAILER, VAN, BUS, CAR, MOTORCYCLE, BOAT, SHIP, AIRPLANE, HELICOPTER, TRAIN, TANKER, CONTAINER_SHIP, AMBULANCE, FIRE_TRUCK, POLICE_CAR, TAXI, MINIBUS, COACH, ELECTRIC_SCOOTER, BICYCLE, FORKLIFT, CRANE, AMBULANCE_BOAT, HORSE_CARRIAGE, REFRIGERATED_TRUCK, GARBAGE_TRUCK, CONSTRUCTION_VEHICLE

}
